project:
  type: website
  output-dir: docs

render:
  - "*.qmd"

website:
  title: "Roy Plant–Microbiome Lab"

  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home

      - href: about.qmd
        text: Principal Investigator

      - text: Research
        menu:
          - text: Research Areas
            href: research.qmd
          - text: Projects
            href: projects.qmd

      - href: team.qmd
        text: Team

      - href: join.qmd
        text: Join the Lab

      - href: publications.qmd
        text: Publications

      - href: news.qmd
        text: News

      - href: contact.qmd
        text: Contact

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: article
    include-after-body: footer.html